version: '3.9'

services:
  # -------------------------
  # MSSQL Database
  # -------------------------
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "sanitize1"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./db-init:/db-init
    command: >
      /bin/bash -c "/opt/mssql/bin/sqlservr & sleep 20 &&
      /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'sanitize1' -i /db-init/init.sql &&
      wait"

  # -------------------------
  # Word Sanitizer Microservice
  # -------------------------
  word-sanitizer-service:
    build: ./word-sanitizer-service
    container_name: word-sanitizer-service
    ports:HO
      - "8080:8080"
    depends_on:
      - mssql
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://mssql:1433;databaseName=sanitizerdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: sanitize1


# -------------------------
# Volumes
# -------------------------
volumes:
  mssql_data:
