spring:
  application:
    name: word-sanitizer-service

  datasource:
    url: jdbc:sqlserver://mssql:1433;databaseName=sanitizerdb
    username: sa
    password: sanitize1
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

