spring:
  application:
    name: word-sanitizer-service

  datasource:
    url: "jdbc:sqlserver://mssql:1433;databaseName=sanitizerdb;encrypt=false;trustServerCertificate=true;"
    username: sa
    password: San1tize_2025
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      connection-timeout: 30000       # wait max 30s for a connection
      maximum-pool-size: 5
      initialization-fail-timeout: -1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
